#!/bin/sh

#
#        (c) 2006,2008 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#

HOSTNAME=`hostname`
echo $HOSTNAME
# TODO: this is DEBCONF8 specific
[ -f /usr/share/doc/debconf-video-common/conf/dc8/default-$HOSTNAME ] || exit 0
echo fu
source /etc/default/debconf-video.passwd || exit 1
echo bar
cp /usr/share/doc/debconf-video-common/conf/dc8/default-$HOSTNAME /etc/default/debconf-video
echo blub
# #HOSTNAME# gets replaced by $HOSTNAME and so on...
echo bra
sed -i "s/#ICECASS_PASS#/$ICECASS_PASS/" /etc/default/debconf-video
sed -i "s/#DATABASE_PASSWORD#/$DATABASE_PASSWORD/" /etc/default/debconf-video

