#!/bin/sh

#
#        (c) 2006,2008 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#

# TODO: this is DEBCONF8 specific
[ -f /usr/share/doc/debconf-video-common/conf/dc8/default-$HOSTNAME ] || exit 0

source /etc/default/debconf-video.passwd || exit 1

cp /usr/share/doc/debconf-video-common/conf/dc8/default-$HOSTNAME /etc/default/debconf-video

# #HOSTNAME# gets replaced by $HOSTNAME and so on...

sed -i "s/#ICECASS_PASS#/$ICECASS_PASS/" /etc/default/debconf-video
sed -i "s/#DATABASE_PASSWORD#/$DATABASE_PASSWORD/" /etc/default/debconf-video

