#!/bin/sh

#
#        (c) 2006-2013 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#

fcopy -M /etc/default/cpufrequtils
[ -f /etc/init.d/cpufrequtils ] && /etc/init.d/cpufrequtils reload
