#!/bin/bash

#
#        (c) 2006,2008 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#


export HOSTNAME=`hostname`
export RELAY="homer"

# #HOSTNAME# gets replaced by $HOSTNAME and so on...

sed -i "s/#HOSTNAME#/$HOSTNAME/" $2
sed -i "s/#RELAY#/$RELAY/" $2

