#! /bin/sh

#
#        (c) 2008 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#

mkdir -p /etc/ssh/userkeys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBLa0ujvmwvETWBh39X2GiqbyJQuZl6d808ALvMMwE/JehyW7hUW3i+c5laHKEQVCWCaT8GUvGNNBvdUNVoOf1JMRY7ScMatV15avuAjHemhQMDbxFjtP93cDUh2hvEasFyUCi7lBVBVHy3YH/JRov2mkG7+BmAV7FjtTpXcAIv4tXkHSddi3PwNjS4nBUTBr/g64TISTEk691ME2EKhX4OxzGnSUBuLK7IMq366wCCMZknHrdAFClaxoZ8D2YPdlDTo2C/PMJ79nZ6iIF235pw+ErhQO7xtfiIpukik1/5cqbd6+ykP3nP7W2M3IpfghY9oqLbhtwte5/r12Ix7S3 dvswitch@scratchy" > /etc/ssh/userkeys/dvswitch
chown 1053.1008 /etc/ssh/userkeys/dvswitch
chmod 600 /etc/ssh/userkeys/dvswitch

# brute force
ln -sf /etc/ssh/userkeys/ /var/keys

