#! /bin/sh

# (c) Thomas Lange, 2001-2005, lange@debian.org

error=0 ; trap "error=$((error|1))" ERR

echo $time_zone    > /etc/timezone
ln -fs /usr/share/zoneinfo/${time_zone} /etc/localtime

fcopy -iM /etc/motd /etc/network/interfaces

exit $error
