#! /bin/bash

#
#        (c) 2006-2013 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#

# we normally get this group from ldap
USER=dvswitch
$ROOTCMD adduser --quiet --disabled-password --uid 1053 --gecos "" $USER
$ROOTCMD addgroup --quiet --gid 1008 dc-video || true

$ROOTCMD mkdir -p /home/$USER/.ssh
$ROOTCMD touch /home/$USER/.ssh/authorized_keys
$ROOTCMD chown -R $USER.$USER /home/$USER/.ssh
$ROOTCMD chmod 700 /home/$USER/.ssh

# the videoteam group which owns the raw1394 device etc
for i in dialout cdrom floppy audio video plugdev powerdev nvram netdev dc-video ; do $ROOTCMD adduser --quiet $USER $i ; done
  
