#!/bin/bash

mkdir -m 700 -p /root/.ssh

[ -f /root/.ssh/authorized_keys ] || touch /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys
chown -R root.root /root/.ssh

# for udldap
mkdir -p /etc/ssh/userkeys
ln -sf /etc/ssh/userkeys/ /var/keys

