#!/bin/sh

if ! echo "$IFACE" | egrep -q '^(br|eth)'; then
	exit 0
fi

iptables -F INPUT
iptables -A INPUT -s 172.31.1.0/22 -j ACCEPT   # VideoTeam Private
iptables -A INPUT -s 80.83.52.176/29 -j ACCEPT # VideoTeam Public
iptables -A INPUT -s 80.83.48.0/22 -j ACCEPT   # DebConf13 wifi
iptables -A INPUT -s 83.68.216.0/22 -j ACCEPT  # Public LAN
iptables -A INPUT -s 80.83.56.32/27 -j ACCEPT  # Server LA
iptables -A INPUT -s 72.14.176.206 -p tcp --dport 8000 -j ACCEPT  # krusty
iptables -A INPUT -s 86.59.21.37 -p tcp --dport 8000 -j ACCEPT    # Rhonda
iptables -A INPUT -j DROP

ip6tables -F INPUT
ip6tables -A INPUT -s fe80::/10 -j ACCEPT  # Link-local
ip6tables -A INPUT -s 2600:3c00::f03c:91ff:fe96:35d3 -p tcp --dport 8000 -j ACCEPT  # krusty
ip6tables -A INPUT -j DROP
