#!/bin/sh

if ! echo "$IFACE" | egrep -q '^(br|eth)'; then
	exit 0
fi

for prog in iptables ip6tables; do
	$prog -F INPUT
	$prog -A INPUT -i lo -j ACCEPT
done

iptables -A INPUT -s 172.31.1.0/22 -j ACCEPT   # VideoTeam Private
iptables -A INPUT -s 80.83.52.176/29 -j ACCEPT # VideoTeam Public
iptables -A INPUT -s 80.83.48.0/22 -j ACCEPT   # DebConf13 wifi
iptables -A INPUT -s 83.68.216.0/22 -j ACCEPT  # Public LAN
iptables -A INPUT -s 80.83.56.32/27 -j ACCEPT  # Server LA
ip6tables -A INPUT -s fe80::/10 -j ACCEPT      # Link-local

for prog in iptables ip6tables; do
	# Password SSH is disabled
	$prog -A INPUT -p tcp --dport 22 -j ACCEPT
	$prog -A INPUT -p tcp --dport 2222 -j ACCEPT
	$prog -A INPUT -p icmp -j ACCEPT
	$prog -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	$prog -A INPUT -j DROP
done
