#!/bin/sh

DATABASE_PASSWORD=unset
if [ -e /etc/default/debconf-video-local ]; then
	. /etc/default/debconf-video-local
fi

sed -i "s/#DATABASE_PASSWORD#/$DATABASE_PASSWORD/" $2
sed -i "s/#ICECAST_PASSWORD#/$ICECAST_PASSWORD/" $2
