#! /bin/bash

# assign classes for hosts at debconf11
# `hostname -f` doesnt return proper results (before running fai :)

#
# the class DEBCONF11 is reserved for machines at the venue...
#

case $HOSTNAME in
   selma|patty|jackie|itchy|scratchy|blinky|barney|lisa|todd)
		echo "FAIBASE DEBCONF DEBCONF11 VIDEO" ;;
esac

case $HOSTNAME in
   selma|patty|jackie|itchy|scratchy|blinky)
		echo "ELITEBOOK" ;;
esac

case $HOSTNAME in
   homer|dc11fw|freeswitch)
		echo "FAIBASE DEBCONF DEBCONF11" ;;
esac

#case $HOSTNAME in
#   dolph)	echo "IPW2X00"
#esac

case $HOSTNAME in
   patty|itchy|jackie|blinky) 
   		echo "CAPTURE";;
   selma|scratchy) 
   		echo "XORG CAPTURE DVSWITCH";;
   todd) 
   		echo "ENCODING";;
   lisa)
   		echo "ICECAST";;
   barney)
   		echo "STORAGE";;
esac

case $HOSTNAME in
   barney) 
   		echo "PENTA";;
esac


#case $HOSTNAME in
#   selma) 
#   		echo "BRIDGE";;
#esac

case $HOSTNAME in 
   selma|patty|jackie|itchy|scratchy|blinky|todd|barney|lisa)
   		echo "DVSWITCHPUBKEY";;
esac

# post-processing after debconf9 at home, do not define DEBCONF8 here
#case $HOSTNAME in
#   io)
#		echo "FAIBASE DEBCONF VIDEO ENCODING STORAGE" ;;
#esac


