#! /bin/sh

# assign classes for hosts at debconf10
# `hostname -f` doesnt return proper results (before running fai :)

#
# the class DEBCONF10 is reserved for machines at the venue...
#

case $HOSTNAME in
   selma|patty|itchy|scratchy|barney|lisa|ned|rod|todd|dolph|jimbo|kearney)
		echo "FAIBASE DEBCONF DEBCONF10 VIDEO" ;;
esac

#case $HOSTNAME in
#   dolph)	echo "IPW2X00"
#esac

case $HOSTNAME in
   patty|itchy) 
   		echo "CAPTURE";;
   selma|scratchy) 
   		echo "XORG CAPTURE DVSWITCH";;
   ned|rod|todd) 
   		echo "ENCODING";;
   dolph|jimbo|kearney)
   		echo "XORG REVIEW";;
   lisa)
   		echo "ICECAST";;
   barney)
   		echo "STORAGE ENCODING";;
esac

#case $HOSTNAME in
#   selma) 
#   		echo "BRIDGE";;
#esac

case $HOSTNAME in 
   selma|patty|itchy|scratchy|ned|rod|todd|barney)
   		echo "DVSWITCHPUBKEY";;
esac

# post-processing after debconf9 at home, do not define DEBCONF8 here
#case $HOSTNAME in
#   io)
#		echo "FAIBASE DEBCONF VIDEO ENCODING STORAGE" ;;
#esac


