#! /bin/sh

# assign classes for hosts at debconf9
# `hostname -f` doesnt return proper results (before running fai :)

#
# the class DEBCONF9 is reserved for machines at the venue...
#

case $HOSTNAME in
   selma|patty|itchy|scratchy|daffy|barney|mrwhite|lisa|marge)
		echo "FAIBASE DEBCONF DEBCONF9 VIDEO" ;;
esac

case $HOSTNAME in
   patty)	echo "IPW2X00"

case $HOSTNAME in
   selma|scratchy|mrwhite) 
   		echo "XORG";;
esac

case $HOSTNAME in
   daffy) 
   		echo "ENCODING";;
   marge|patty|itchy|scratchy) 
   		echo "CAPTURE";;
   mrwhite)
   		echo "REVIEW";;
   lisa)
   		echo "ICECAST";;
   barney)
   		echo "STORAGE";;
esac

case $HOSTNAME in
   selma|scratchy) 
   		echo "DVSWITCH";;
esac
#case $HOSTNAME in
#   selma) 
#   		echo "BRIDGE";;
#esac

case $HOSTNAME in 
   selma|patty|itchy|scratchy|marge|daffy|barney)
   		echo "DVSWITCHPUBKEY";;
esac

# post-processing after debconf9 at home, do not define DEBCONF8 here
#case $HOSTNAME in
#   io)
#		echo "FAIBASE DEBCONF VIDEO ENCODING STORAGE" ;;
#esac


