#! /bin/bash

# assign classes for hosts at debconf11
# `hostname -f` doesnt return proper results (before running fai :)

#
# the class DEBCONF11 is reserved for machines at the venue...
#

case $HOSTNAME in
   selma|patty|jackie|sideshow|itchy|scratchy|blinky|barney|lisa|ned|rod|todd|dolph|jimbo|kearney)
		echo "FAIBASE DEBCONF DEBCONF11 VIDEO" ;;
esac

#case $HOSTNAME in
#   dolph)	echo "IPW2X00"
#esac

case $HOSTNAME in
   patty|itchy|jackie|blinky|sideshow) 
   		echo "CAPTURE";;
   selma|scratchy) 
   		echo "XORG CAPTURE DVSWITCH STORAGE";;
   ned|todd) 
   		echo "ENCODING";;
   dolph|jimbo|kearney)
   		echo "XORG REVIEW";;
   lisa)
   		echo "ICECAST";;
   barney|rod)
   		echo "STORAGE";;
esac

case $HOSTNAME in
   selma|scratchy) 
   		echo "NVIDIA";;
   barney) 
   		echo "PENTA";;
esac


#case $HOSTNAME in
#   selma) 
#   		echo "BRIDGE";;
#esac

case $HOSTNAME in 
   selma|patty|jackie|sideshow|itchy|scratchy|blinky|ned|rod|todd|barney)
   		echo "DVSWITCHPUBKEY";;
esac

# post-processing after debconf9 at home, do not define DEBCONF8 here
#case $HOSTNAME in
#   io)
#		echo "FAIBASE DEBCONF VIDEO ENCODING STORAGE" ;;
#esac


