#! /bin/sh

exit 0

# some classes for all hosts
echo "FAIBASE DEBCONF VIDEO" 

# assign classes for hosts at debconf7
case `hostname -f` in
   *.dc7.debconf.org)
		echo "DEBCONF7" ;;
esac

case $HOSTNAME in
   mickey|daffy|donald) 
   		echo "ENCODING";;
   selma|mrwhite) 
   		echo "BRIDGE";;
esac
case $HOSTNAME in
   selma|shadow|hashbaz|patty|mrwhite|itchy|scratchy) 
   		echo "CAPTURE";;
esac
case $HOSTNAME in
   selma|mrwhite|itchy|scratchy) 
   		echo "DVSWITCH";;
esac


# temp. fileserver
case $HOSTNAME in
   abe) 
   		echo "ENCODING";;
esac

