#! /bin/sh

# assign classes for hosts at debconf8
# `hostname -f` doesnt return proper results
case $HOSTNAME in
   selma|patty|itchy|scratchy|daffy|barney|mrwhite|lisa|marge)
		echo "FAIBASE DEBCONF DEBCONF8 VIDEO" ;;
esac

case $HOSTNAME in
   selma|scratchy|mrwhite) 
   		echo "XORG";;
esac

case $HOSTNAME in
   daffy) 
   		echo "ENCODING";;
   marge|patty|itchy|scratchy) 
   		echo "CAPTURE";;
   mrwhite)
   		echo "REVIEW";;
   lisa)
   		echo "ICECAST";;
esac
# "barney" is its own class

case $HOSTNAME in
   selma|scratchy) 
   		echo "DVSWITCH";;
esac
#case $HOSTNAME in
#   selma) 
#   		echo "BRIDGE";;
#esac


case $HOSTNAME in 
   selma|patty|itchy|scratchy|marge|daffy|barney)
   		echo "DVSWITCHPUBKEY";;
esac

