#! /bin/sh

# some classes for all hosts
echo "FAIBASE DEBCONF VIDEO" 

# assign classes for hosts at debconf8
# `hostname -f` doesnt return proper results
case $HOSTNAME in
   selma|patty|itchy|scratchy|daffy|barney|mrwhite)
		echo "DEBCONF8" ;;
esac

case $HOSTNAME in
   daffy) 
   		echo "ENCODING";;
   selma|patty|itchy|scratchy) 
   		echo "CAPTURE";;
   mrwhite)
   		echo "REVIEW";;
esac

case $HOSTNAME in
   selma|scratchy) 
   		echo "DVSWITCH";;
esac



