#! /bin/sh

# assign classes for hosts at fosdem 2009
# `hostname -f` doesnt return proper results (before running fai :)

#
#

case $HOSTNAME in
   selma|patty|ned)
		echo "FAIBASE DEBCONF VIDEO FOSDEM" ;;
esac

case $HOSTNAME in
   selma) 
   		echo "XORG";;
esac

case $HOSTNAME in
   ned) 
   		echo "ENCODING";;
   selma|patty|ned) 
   		echo "CAPTURE";;
   ned)
   		echo "ICECAST";;
   selma)
   		echo "STORAGE";;
esac

case $HOSTNAME in
   selma) 
   		echo "DVSWITCH";;
esac

case $HOSTNAME in 
   selma|patty|ned)
   		echo "DVSWITCHPUBKEY";;
esac


