#! /bin/bash

# assign classes for hosts at fosdem 2013
# `hostname -f` doesnt return proper results (before running fai :)

#
#

case $HOSTNAME in
  twinpact?|spare?)
		echo "FAIBASE DEBCONF VIDEO FOSDEM" ;;
esac


exit 0

case $HOSTNAME in
   r?grab*|r?dvswitch*)
		echo "FAIBASE DEBCONF VIDEO FOSDEM" ;;
esac

case $HOSTNAME in
   r?dvswitch*) 
   		echo "XORG";;
esac

case $HOSTNAME in
#   ned) 
#   		echo "ENCODING";;
   r?grab*) 
   		echo "CAPTURE";;
#   ned)
#   		echo "ICECAST";;
esac

case $HOSTNAME in
   r?dvswitch*) 
   		echo "DVSWITCH STORAGE";;
esac

case $HOSTNAME in 
   r?grab*|r?dvswitch*)
   		echo "DVSWITCHPUBKEY";;
esac


