#! /bin/bash

# assign classes for hosts at fosdem 2013
# `hostname -f` doesnt return proper results (before running fai :)

#
#

case $HOSTNAME in
  twinpact?|spare?|dvswitch?|encoder?)
		echo "FAIBASE VIDEO FOSDEM" ;;
esac

case $HOSTNAME in
   dvswitch?) 	echo "XORG DVSWITCH CAPTURE";;
   twinpact?) 	echo "CAPTURE";;
esac
#unused CLASSES: ENCODING ICECAST

case $HOSTNAME in
   twinpact?) 	echo "STORAGE";;
esac

case $HOSTNAME in 
   twinpact?|dvswitch?)
   		echo "DVSWITCHPUBKEY";;
esac


