#! /bin/bash

# assign classes for hosts at fosdem 2014
# `hostname -f` doesnt return proper results (before running fai :)

#
#

case $HOSTNAME in
  video?|r*master|r*slave)
		# FOSDEM is kinda debconf...
		echo "FAIBASE DEBCONF VIDEO FOSDEM" 
   		echo "DVSWITCHPUBKEY"
		;;
esac

case $HOSTNAME in
   video?)	echo "BONDING";;
   r*master) 	echo "CAPTURE STORAGE XORG DVSWITCH";;
   r*slave) 	echo "CAPTURE";;
esac
#unused CLASSES: ENCODING ICECAST

