#! /bin/bash

# assign classes for hosts at fosdem 2014
# `hostname -f` doesnt return proper results (before running fai :)

#
#

case $HOSTNAME in
  video?|r*master|r*slave|spare*)
		# FOSDEM is kinda debconf...
		echo "FAIBASE VIDEO FOSDEM" 
		;;
esac

case $HOSTNAME in
   video?)		echo "BONDING"
			;;
   r*master) 		# ACTIVEX is only used to fire up nodm
			echo "CAPTURE STORAGE XORG DVSWITCH"
	                echo "DVSWITCHPUBKEY"
			;;
   r*slave|spare) 	echo "CAPTURE DVSWITCH XORG NOX"
	                echo "DVSWITCHPUBKEY"
			;;
esac
case $HOSTNAME in
   video1)	echo "XORG";;
   *slave)	echo "SLAVE";;
esac
#unused CLASSES: ENCODING ICECAST

