#! /bin/sh

#
#        (c) 2006, 2008 Holger Levsen         holger@layer-acht.org
#        GPL2 licenced
#

#
# smart munin plugins
#
for i in hda hdb hdc sda sdb sdc sdd sde sdf ; do {
	[ -b /dev/$i ] && ln -sf /usr/share/munin/plugins/smart_ $target/etc/munin/plugins/smart_$i 
} ; done
ls /etc/munin/plugins/smart_??? | grep smart > /dev/null 2>&1 && {
	sed -i "s/#start_smartd/start_smartd/" $target/etc/default/smartmontools 
	$ROOTCMD /etc/init.d/smartmontools reload
	$ROOTCMD ln -sf /usr/share/munin/plugins/hddtemp_smartctl /etc/munin/plugins/hddtemp_smartctl
	$ROOTCMD /etc/init.d/munin-node restart
}

